<?php

declare(strict_types=1);

namespace App\Services;

use App\Exceptions\AlbumQuotaReachedException;
use App\Jobs\GenerateImageVariants;
use App\Models\Face;
use App\Models\FacePhoto;
use App\Support\ImageVariantGenerator;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class PhotoAlbumService
{
    private const STORAGE_PATH = 'avatars/faces/albums';

    /**
     * Add a photo to a Face's album. The request only stores the original and
     * the row; all variants (150/800/400/1600) are generated by a queued job
     * dispatched after commit — accessors fall back to the original meanwhile.
     *
     * @throws AlbumQuotaReachedException If album quota is reached for this Face's tier
     */
    public function addPhoto(Face $face, UploadedFile $photo): FacePhoto
    {
        // Generate unique filename with UUID
        $extension = $photo->getClientOriginalExtension() ?: 'jpg';
        $filename = Str::uuid()->toString().'.'.$extension;

        // Use transaction to ensure atomicity - cleanup files on DB failure
        return DB::transaction(function () use ($face, $photo, $filename) {
            // Re-check entitlement-aware quota inside the transaction, before any
            // filesystem write, to close the race between FormRequest validation
            // and service execution. DB transactions do not roll back filesystem
            // writes, so the quota check must run first.
            $currentCount = $face->photos()->count();
            $limit = app(FaceEntitlementService::class)->capabilities($face)->maxAlbumPhotos;
            if ($currentCount >= $limit) {
                throw new AlbumQuotaReachedException($limit);
            }

            $nextPosition = $currentCount + 1;

            // Store original photo
            Storage::disk('public')->putFileAs(self::STORAGE_PATH, $photo, $filename);

            try {
                // Create FacePhoto record — variant columns stay null until the job fills them
                /** @var FacePhoto $facePhoto */
                $facePhoto = FacePhoto::create([
                    'face_id' => $face->id,
                    'filename' => $filename,
                    'position' => $nextPosition,
                ]);

                // afterCommit job: runs only if the transaction commits, so it
                // always sees the row (and never runs for a rolled-back photo).
                dispatch(GenerateImageVariants::forModel($facePhoto));

                return $facePhoto;
            } catch (\Throwable $e) {
                // Clean up the stored original on failure (DB rollback does not
                // roll back filesystem writes)
                Storage::disk('public')->delete(self::STORAGE_PATH.'/'.$filename);
                throw $e;
            }
        });
    }

    /**
     * Delete a photo from a Face's album.
     */
    public function deletePhoto(FacePhoto $photo): bool
    {
        $face = $photo->face;

        if (! $face instanceof Face) {
            return false;
        }

        // File cleanup (original + every variant) is driven by the shared
        // catalog in ImageVariantGenerator.
        app(ImageVariantGenerator::class)->deleteFiles($photo);

        // Delete database record
        $photo->delete();

        // Reorder remaining photos to fill the gap
        $this->reorderAfterDelete($face);

        return true;
    }

    /**
     * Reorder photos for a Face.
     *
     * @param  array<int>  $order  Array of photo IDs in desired order
     *
     * @throws \Exception If IDs don't match Face's photos
     */
    public function reorderPhotos(Face $face, array $order): void
    {
        $photos = $face->photos()->get();
        $photoIds = $photos->pluck('id')->toArray();

        // Validate all IDs belong to this face
        foreach ($order as $id) {
            if (! in_array($id, $photoIds)) {
                throw new \Exception('Photo ID '.$id.' does not belong to this Face');
            }
        }

        // Validate all face photos are in the order array
        if (count($order) !== count($photoIds)) {
            throw new \Exception('Order array must contain all photo IDs');
        }

        // Update positions in a transaction
        DB::transaction(function () use ($order) {
            // First, set all positions to high temporary values to avoid unique constraint violations
            // Using 1000 + index as temp value (max album positions reach 6 for Élite; the offset stays clear of real positions)
            foreach ($order as $index => $photoId) {
                FacePhoto::where('id', $photoId)->update(['position' => 1000 + $index]);
            }

            // Then, set them to the correct positions
            foreach ($order as $index => $photoId) {
                FacePhoto::where('id', $photoId)->update(['position' => $index + 1]);
            }
        });
    }

    /**
     * Get all photos for a Face, ordered by position.
     *
     * @return Collection<int, FacePhoto>
     */
    public function getPhotos(Face $face): Collection
    {
        /** @var Collection<int, FacePhoto> $photos */
        $photos = $face->photos()->orderBy('position')->get();

        return $photos;
    }

    /**
     * Reorder photos after a deletion to fill the gap.
     */
    private function reorderAfterDelete(Face $face): void
    {
        $photoIds = $face->photos()->orderBy('position')->pluck('id')->toArray();

        if (empty($photoIds)) {
            return;
        }

        DB::transaction(function () use ($photoIds) {
            // First, set all to high temporary values to avoid unique constraint violations
            foreach ($photoIds as $index => $photoId) {
                FacePhoto::where('id', $photoId)->update(['position' => 1000 + $index]);
            }

            // Then, set them to the correct positions
            foreach ($photoIds as $index => $photoId) {
                FacePhoto::where('id', $photoId)->update(['position' => $index + 1]);
            }
        });
    }
}
