<?php

declare(strict_types=1);

namespace App\Services;

use App\Jobs\GenerateImageVariants;
use App\Models\Producer;
use App\Support\ImageVariantGenerator;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class ProducerProfilePhotoService
{
    private const STORAGE_PATH = 'avatars/producers';

    /**
     * Upload a profile photo for a Producer. The request only stores the
     * original and the row; all variants (150/800/400/1600) are generated by
     * a queued job — accessors fall back to the original in the meantime.
     *
     * @return array{photo: string}
     */
    public function uploadProfilePhoto(Producer $producer, UploadedFile $photo): array
    {
        $this->deleteProfilePhoto($producer);

        $extension = $photo->getClientOriginalExtension() ?: 'jpg';
        $filename = Str::uuid()->toString().'.'.$extension;

        Storage::disk('public')->putFileAs(self::STORAGE_PATH, $photo, $filename);

        // Variant columns stay null until the job fills them
        $producer->update([
            'profile_photo' => $filename,
            'profile_photo_thumbnail' => null,
            'profile_photo_medium' => null,
            'profile_photo_grid' => null,
            'profile_photo_large' => null,
        ]);

        dispatch(GenerateImageVariants::forModel($producer));

        return [
            'photo' => $filename,
        ];
    }

    /**
     * Delete profile photo and all its variants for a Producer.
     */
    public function deleteProfilePhoto(Producer $producer): bool
    {
        // File cleanup (original + every variant) is driven by the shared
        // catalog in ImageVariantGenerator — no per-variant paths to keep in
        // sync here.
        $deleted = app(ImageVariantGenerator::class)->deleteFiles($producer);

        if ($producer->profile_photo
            || $producer->profile_photo_thumbnail
            || $producer->profile_photo_medium
            || $producer->profile_photo_grid
            || $producer->profile_photo_large) {
            $producer->update([
                'profile_photo' => null,
                'profile_photo_thumbnail' => null,
                'profile_photo_medium' => null,
                'profile_photo_grid' => null,
                'profile_photo_large' => null,
            ]);
        }

        return $deleted;
    }
}
