<?php

declare(strict_types=1);

namespace App\Services;

use App\Jobs\GenerateImageVariants;
use App\Models\Face;
use App\Support\ImageVariantGenerator;
use App\Support\UploadedMedia;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;

class ProfilePhotoService
{
    private const STORAGE_PATH = 'avatars/faces';

    /**
     * Upload a profile photo for a Face. The request only stores the original
     * and the row; all variants (150/800/400/1600) are generated by a queued
     * job — accessors fall back to the original in the meantime.
     *
     * @return array{photo: string}
     */
    public function uploadProfilePhoto(Face $face, UploadedFile $photo): array
    {
        // Original nettoyé (EXIF supprimé), extension dérivée du contenu
        $filename = UploadedMedia::storeImage('public', self::STORAGE_PATH, $photo, 'photo');

        // Relit le modèle : des variantes réclamées entre-temps par le job précédent doivent aussi
        // être supprimées. L'ancienne photo n'est supprimée qu'APRÈS le succès de l'écriture DB.
        $face->refresh();
        $generator = app(ImageVariantGenerator::class);
        $oldFiles = $generator->candidateFiles($face);

        // UNE seule mise à jour vers le nouveau nom (variant columns stay null until the job fills
        // them) : pas d'état intermédiaire « sans photo ».
        try {
            $face->update([
                'profile_photo' => $filename,
                'profile_photo_thumbnail' => null,
                'profile_photo_medium' => null,
                'profile_photo_grid' => null,
                'profile_photo_large' => null,
            ]);
        } catch (\Throwable $e) {
            Storage::disk('public')->delete(self::STORAGE_PATH.'/'.$filename); // l'ancienne photo reste intacte

            throw $e;
        }

        Storage::disk(ImageVariantGenerator::diskFor($face))->delete($oldFiles);

        dispatch(GenerateImageVariants::forModel($face));

        return [
            'photo' => $filename,
        ];
    }

    /**
     * Delete profile photo and all its variants for a Face.
     */
    public function deleteProfilePhoto(Face $face): bool
    {
        // Relit les colonnes (variantes réclamées par un job depuis le chargement du modèle).
        if ($face->exists) {
            $face->refresh();
        }

        // File cleanup (original + every variant) is driven by the shared
        // catalog in ImageVariantGenerator — no per-variant paths to keep in
        // sync here.
        $deleted = app(ImageVariantGenerator::class)->deleteFiles($face);

        // Clear the database fields
        if ($face->profile_photo
            || $face->profile_photo_thumbnail
            || $face->profile_photo_medium
            || $face->profile_photo_grid
            || $face->profile_photo_large) {
            $face->update([
                'profile_photo' => null,
                'profile_photo_thumbnail' => null,
                'profile_photo_medium' => null,
                'profile_photo_grid' => null,
                'profile_photo_large' => null,
            ]);
        }

        return $deleted;
    }
}
