<?php

declare(strict_types=1);

namespace App\Services;

use App\Jobs\GenerateImageVariants;
use App\Models\Face;
use App\Support\ImageVariantGenerator;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class ProfilePhotoService
{
    private const STORAGE_PATH = 'avatars/faces';

    /**
     * Upload a profile photo for a Face. The request only stores the original
     * and the row; all variants (150/800/400/1600) are generated by a queued
     * job — accessors fall back to the original in the meantime.
     *
     * @return array{photo: string}
     */
    public function uploadProfilePhoto(Face $face, UploadedFile $photo): array
    {
        // Delete old photos if they exist
        $this->deleteProfilePhoto($face);

        // Generate unique filename with UUID
        $extension = $photo->getClientOriginalExtension() ?: 'jpg';
        $filename = Str::uuid()->toString().'.'.$extension;

        // Store original photo using the public disk
        Storage::disk('public')->putFileAs(self::STORAGE_PATH, $photo, $filename);

        // Update Face model — variant columns stay null until the job fills them
        $face->update([
            'profile_photo' => $filename,
            'profile_photo_thumbnail' => null,
            'profile_photo_medium' => null,
            'profile_photo_grid' => null,
            'profile_photo_large' => null,
        ]);

        dispatch(GenerateImageVariants::forModel($face));

        return [
            'photo' => $filename,
        ];
    }

    /**
     * Delete profile photo and all its variants for a Face.
     */
    public function deleteProfilePhoto(Face $face): bool
    {
        // File cleanup (original + every variant) is driven by the shared
        // catalog in ImageVariantGenerator — no per-variant paths to keep in
        // sync here.
        $deleted = app(ImageVariantGenerator::class)->deleteFiles($face);

        // Clear the database fields
        if ($face->profile_photo
            || $face->profile_photo_thumbnail
            || $face->profile_photo_medium
            || $face->profile_photo_grid
            || $face->profile_photo_large) {
            $face->update([
                'profile_photo' => null,
                'profile_photo_thumbnail' => null,
                'profile_photo_medium' => null,
                'profile_photo_grid' => null,
                'profile_photo_large' => null,
            ]);
        }

        return $deleted;
    }
}
