type SelectOption = {
  value: string
  label: string
}

const BENIN_CITIES = [
  'Abomey',
  'Abomey-Calavi',
  'Adja-Ouèrè',
  'Adjarra',
  'Adjohoun',
  'Agbangnizoun',
  'Aguégués',
  'Akpro-Missérété',
  'Allada',
  'Aplahoué',
  'Athiémé',
  'Avrankou',
  'Banikoara',
  'Bantè',
  'Bassila',
  'Bembèrèkè',
  'Bohicon',
  'Bonou',
  'Bopa',
  'Boukoumbé',
  'Cobly',
  'Comè',
  'Copargo',
  'Cotonou',
  'Covè',
  'Dangbo',
  'Dassa-Zoumè',
  'Djakotomey',
  'Djidja',
  'Djougou',
  'Dogbo',
  'Glazoué',
  'Gogounou',
  'Grand-Popo',
  'Houéyogbé',
  'Ifangni',
  'Kalalé',
  'Kandi',
  'Karimama',
  'Kérou',
  'Kétou',
  'Klouékanmè',
  'Kouandé',
  'Kpomassè',
  'Lalo',
  'Lokossa',
  'Malanville',
  'Matéri',
  'Natitingou',
  "N'Dali",
  'Nikki',
  'Ouidah',
  'Ouinhi',
  'Ouaké',
  'Ouèssè',
  'Parakou',
  'Pehunco',
  'Pèrèrè',
  'Pobè',
  'Porto-Novo',
  'Sakété',
  'Savalou',
  'Savè',
  'Ségbana',
  'Sèmè-Kpodji',
  'Sinendé',
  'Sô-Ava',
  'Tanguiéta',
  'Tchaourou',
  'Toffo',
  'Tori-Bossito',
  'Toucountouna',
  'Toviklin',
  'Za-Kpota',
  'Zagnanado',
  'Zè',
  'Zogbodomey',
] as const

export const BENIN_CITY_OPTIONS: SelectOption[] = [...BENIN_CITIES]
  .map((city) => ({
    value: city,
    label: city,
  }))
  .sort((left, right) => left.label.localeCompare(right.label, 'fr', { sensitivity: 'base' }))

export const BENIN_CITY_VALUES = new Set(BENIN_CITY_OPTIONS.map((option) => option.value))
